title: Dibyendu Majumder # your name (or website title) here
logo: "/images/self.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  15+ years of technology executive leadership experience in enterprise application architecture with world-class asset management, financial and proprietary trading firms 
  <br><br>
  Experience undertaking end to end responsibility for leading and carrying out the technology vision leading all aspects of technology strategy and growth  
  <br><br>
  <a href="https://www.linkedin.com/in/dibyendu-majumder-3725142/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-CGQ1DPKNRY # your Google Analytics tracking ID here
